version: '3.8'

services:
  covidapp:
    image: analythium/covidapp-shiny:minimal
    restart: unless-stopped
    ports:
      - 80:3838
  shinyproxy:
    image: openanalytics/shinyproxy-snapshot
    user: root:root
    hostname: shinyproxy
    restart: unless-stopped
    ports:
      - 8989:8080
  # web:
  #   build: ./app
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./app/:/usr/src/app/
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env  
  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=hello_django
  #     - POSTGRES_PASSWORD=hello_django
  #     - POSTGRES_DB=hello_django_dev
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes: 
     - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    build: ./nginx
    ports:
     - 1337:80